/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package controleprodutos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuris
 */
public class DialogEntradasVendas extends javax.swing.JDialog {
    
    static Connection con;

    /** Creates new form DialogEntradasVendas */
    public DialogEntradasVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpOperacao = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        rbEntrada = new javax.swing.JRadioButton();
        rbSaida = new javax.swing.JRadioButton();
        lblOperacao = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnProcessar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome do Produto", "Marca", "Vendedor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 120));

        grpOperacao.add(rbEntrada);
        rbEntrada.setText("Entrada");
        getContentPane().add(rbEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        grpOperacao.add(rbSaida);
        rbSaida.setText("Saída");
        getContentPane().add(rbSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lblOperacao.setText("Operação:");
        getContentPane().add(lblOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, 560, 10));

        lblQuantidade.setText("Quantidade:");
        getContentPane().add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, -1));

        btnProcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controleprodutos/ícones/icons8-services-24.png"))); // NOI18N
        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controleprodutos/ícones/icons8-password-reset-24.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controleprodutos/ícones/icons8-close-window-24.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
        con = DriverManager.getConnection("jdbc:sqlite:dadosAlmoxarifado.db");
        mostrarDados();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtQuantidade.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        // TODO add your handling code here:
        int linha = tabelaDados.getSelectedRow();
        if ( (validarCampos() == true) && (linha >= 0) ) {
        String sql = "";
        if(rbEntrada.isSelected()){
            sql = "UPDATE produtos SET quantidade=quantidade+? WHERE id=?";
        } else {
            sql = "UPDATE produtos SET quantidade=quantidade-? WHERE id=?";
        }
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, (txtQuantidade.getText()));
            ps.setString(2, tabelaDados.getValueAt(linha, 0).toString());
            ps.execute();
            ps.close();
            mostrarDados();
            txtQuantidade.setText("");
            
            JOptionPane.showMessageDialog(null, "Estoque alterado!");
        } catch (Exception e) {
            e.printStackTrace();
        }
        }    
    }//GEN-LAST:event_btnProcessarActionPerformed

    private void tabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDadosMouseClicked
        // TODO add your handling code here:
        int linha = tabelaDados.getSelectedRow();
        if (linha >= 0){
            try {
                PreparedStatement ps = con.prepareStatement("SELECT * FROM produtos WHERE id=?");
                ps.setString(1, tabelaDados.getValueAt(linha, 0).toString());
                ResultSet rs = ps.executeQuery();

                String id = rs.getString("id");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tabelaDadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEntradasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEntradasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEntradasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEntradasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEntradasVendas dialog = new DialogEntradasVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void setOperacao(int op){
        if (op == 1){
            rbEntrada.setSelected(true);
        } else {
            rbSaida.setSelected(true);
        }
    }
    private boolean validarCampos() {
        if ((txtQuantidade.getText().trim().length() == 0)) {
           return false;
        } try{
             int quantidade = Integer.parseInt(txtQuantidade.getText());
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    private void mostrarDados() {
        
        DialogProdutos dp = new DialogProdutos(null, true);
        
        DecimalFormat df = new DecimalFormat("0.00");
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM produtos");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tabelaDados.getModel();
            model.setRowCount(0); // Limpar Tabela
            while (rs.next()) {
                Object linha[] = {rs.getString("id"), rs.getString("nome"), 
                                  dp.getNomeMarca(rs.getInt("marca")), rs.getString("vendedor"),
                                  rs.getString("quantidade")};
                model.addRow(linha); //Adicionar linha
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup grpOperacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblOperacao;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSaida;
    private javax.swing.JTable tabelaDados;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

}
