/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controleprodutos;

import javax.swing.JOptionPane;

/**
 *
 * @author yuris
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarra = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuProdutos = new javax.swing.JMenuItem();
        menuMovimento = new javax.swing.JMenu();
        menuEntradas = new javax.swing.JMenuItem();
        menuSaidas = new javax.swing.JMenuItem();
        menuDiversos = new javax.swing.JMenu();
        menuCalculadora = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Almoxarifado de TI da Univates");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCadastro.setText("Cadastro");

        menuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuProdutos.setText("Produtos...");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuProdutos);

        menuBarra.add(menuCadastro);

        menuMovimento.setText("Movimento");

        menuEntradas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuEntradas.setText("Entradas...");
        menuEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntradasActionPerformed(evt);
            }
        });
        menuMovimento.add(menuEntradas);

        menuSaidas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuSaidas.setText("Saidas...");
        menuSaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaidasActionPerformed(evt);
            }
        });
        menuMovimento.add(menuSaidas);

        menuBarra.add(menuMovimento);

        menuDiversos.setText("Diversos");

        menuCalculadora.setText("Calculadora");
        menuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalculadoraActionPerformed(evt);
            }
        });
        menuDiversos.add(menuCalculadora);

        menuBarra.add(menuDiversos);

        menuSair.setText("Sair");

        menuSairSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSairSistema.setText("Sair do Sistema...");
        menuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairSistemaActionPerformed(evt);
            }
        });
        menuSair.add(menuSairSistema);

        menuBarra.add(menuSair);

        setJMenuBar(menuBarra);

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        // TODO add your handling code here:
        DialogProdutos dp = new DialogProdutos(this, true);
        dp.setVisible(true);
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void menuEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntradasActionPerformed
        // TODO add your handling code here:
        DialogEntradasVendas dp = new DialogEntradasVendas(this, true);
        dp.setOperacao(1);
        dp.setVisible(true); 
    }//GEN-LAST:event_menuEntradasActionPerformed

    private void menuSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaidasActionPerformed
        // TODO add your handling code here:
        DialogEntradasVendas dp = new DialogEntradasVendas(this, true);
        dp.setOperacao(2);
        dp.setVisible(true); 
    }//GEN-LAST:event_menuSaidasActionPerformed

    private void menuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairSistemaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja sair?",
                "Sair", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuSairSistemaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema de Controle de Almoxarifado de TI na Univates");
    }//GEN-LAST:event_formWindowOpened

    private void menuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalculadoraActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_menuCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCalculadora;
    private javax.swing.JMenu menuDiversos;
    private javax.swing.JMenuItem menuEntradas;
    private javax.swing.JMenu menuMovimento;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuSaidas;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSairSistema;
    // End of variables declaration//GEN-END:variables
}
